version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dhgwpgmbdmqe"
